SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS PLACE;
DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS REVIEW;

CREATE TABLE PLACE (PLACE_ID INT PRIMARY KEY AUTO_INCREMENT, PLACENAME VARCHAR(20));
CREATE TABLE MEMBER(MEMBER_ID INT PRIMARY KEY AUTO_INCREMENT, USERNAME VARCHAR (50), PASSWORD VARCHAR (100), POINT INT);
CREATE TABLE REVIEW(REVIEW_ID INT PRIMARY KEY AUTO_INCREMENT, CONTENT VARCHAR (100), PHOTOIDS VARCHAR (100), TYPE VARCHAR (10), ID_P INT ,ID_M INT, FOREIGN KEY(ID_M) REFERENCES MEMBER(MEMBER_ID),FOREIGN KEY(ID_P) REFERENCES PLACE(PLACE_ID) ON DELETE CASCADE);


INSERT INTO PLACE(PLACENAME) VALUE('제주');
INSERT INTO PLACE(PLACENAME) VALUE('부산');
INSERT INTO PLACE(PLACENAME) VALUE('속초');

INSERT INTO MEMBER(USERNAME, PASSWORD, POINT) VALUES ('박윤수', '1234', 0);

INSERT INTO REVIEW(CONTENT, PHOTOIDS, TYPE, ID_P,ID_M) VALUES ('좋아요', '1234', 'REVIEW',1,1);